### ISSUE TITLE
Danish translation question

### ISSUE THREAD

**Issue by Maxithx666** [qbcore-framework/qb-gangmenu#14]
Hi just a little question. i am not a programmer. but i love QBcore. and i learned alot about how to use it so far. 
I have translated some of the QBcore files. works great so far. I did qb-multicharacter/html/index.html and qb-adminmenu/locales/da.lua
and so on. But about my question for the qb-gangmenu i guess if i should translate the qb-gangmenu, i will need to translate the qb-bossmenu to danish as they are related. I only do client.lua and the label and description lines? 

I hope you will give me a hint about that. even though i am not a programmer. 

Kind regards Maxithx

**Comment by ItsANoBrainer** [comment]
Anything that is shown to the player (notifications, menus, etc) need to be translated, so both client and server. Follow something like this:
https://github.com/qbcore-framework/qb-fitbit/pull/10#pullrequestreview-904963850
